#!/bin/bash

PACKAGE=redis
VERSION=3.0.7
REVISION=agora-`date +%Y%m%d-%H%M`
TARGET="$PACKAGE-$VERSION"
DEPLOY_ROOT=/home/vagrant/debian-packages
DEPLOY_PATH=$DEPLOY_ROOT/`lsb_release -cs`/$PACKAGE/
GIT_USER=`git config --global user.name`
GIT_EMAIL=`git config --global user.email`

sudo apt-get install -y autoconf && \
sudo apt-get install -y curl && \

pushd $TARGET/deps && \
./update-jemalloc.sh 3.6.0 && \

pushd jemalloc && \
./autogen.sh && \
popd && \

make jemalloc && \
make lua && \
make hiredis && \
popd && \

pushd $TARGET && \
make && \

rm -rf /tmp/$TARGET && \
mkdir -p /tmp/$TARGET/usr/ && \
mkdir -p /tmp/$TARGET/etc/redis && \
make install PREFIX=/tmp/$TARGET/usr && \
popd && \

rm -f $TARGET.deb && \
fpm -s dir -t deb -n $PACKAGE -v $VERSION --iteration $REVISION -C /tmp/$TARGET \
  -p $TARGET.deb \
  -d "libc6 (>= 2.14)" \
  -d "adduser" \
  --maintainer "$GIT_USER <$GIT_EMAIL>" \
  --after-install after-install.sh \
  --after-remove after-remove.sh \
  usr etc  && \
echo 'DONE!'
